#let __html__ = html

#let html(..args)        = __html__.elem("html", attrs: args.named(), ..args.pos())
#let head(..args)        = __html__.elem("head", attrs: args.named(), ..args.pos())
#let meta(..args)        = __html__.elem("meta", attrs: args.named(), ..args.pos())
#let link(..args)        = __html__.elem("link", attrs: args.named(), ..args.pos())
#let body(..args)        = __html__.elem("body", attrs: args.named(), ..args.pos())
#let title(..args)       = __html__.elem("title", attrs: args.named(), ..args.pos())
#let script(..args)      = __html__.elem("script", attrs: args.named(), ..args.pos())
#let div(..args)         = __html__.elem("div", attrs: args.named(), ..args.pos())
#let details(..args)     = __html__.elem("details", attrs: args.named(), ..args.pos())
#let summary(..args)     = __html__.elem("summary", attrs: args.named(), ..args.pos())
#let span(..args)        = __html__.elem("span", attrs: args.named(), ..args.pos())
#let figure(..args)      = __html__.elem("figure", attrs: args.named(), ..args.pos())
#let figcaption(..args)  = __html__.elem("figcaption", attrs: args.named(), ..args.pos())
#let a(..args)           = __html__.elem("a", attrs: args.named(), ..args.pos())
#let hr(..args)          = __html__.elem("hr", attrs: args.named(), ..args.pos())
